[build]
builder = "NIXPACKS"
buildCommand = "cd .idea/projeto/backend && npm install"

[deploy]
startCommand = "cd .idea/projeto/backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
